import LegalLayout from '@/components/ui/LegalLayout';

export const metadata = {
  title: 'Privacy Policy',
  description: 'Privacy policy describing how Giovanni Village Resort collects, uses and discloses guest information.',
  alternates: { canonical: '/privacy' },
  openGraph: {
    title: 'Privacy Policy — Giovanni Village Resort',
    description: 'How Giovanni Village handles guest data.',
    url: '/privacy',
    images: ['/images/og/og-default.jpg'],
  },
};

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="March 13, 2024">
      <p>
        This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your
        information when you use the Service and tells you about your privacy rights and how the law protects you.
      </p>
      <p>
        We use your personal data to provide and improve the Service. By using the Service, you agree to the
        collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for you to access our Service or parts of our
          Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a
          party.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo;
          or &ldquo;Our&rdquo; in this Agreement) refers to Giovanni Village, Village Kalapani, Kolar Main Road,
          Bhopal.
        </li>
        <li>
          <strong>Cookies</strong> are small files placed on your computer, mobile device or any other device by a
          website, containing the details of your browsing history.
        </li>
        <li>
          <strong>Country</strong> refers to: Madhya Pradesh, India.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
          digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the
          Company.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or
          from the Service infrastructure itself.
        </li>
        <li>
          <strong>Website</strong> refers to Giovanni Village, accessible from{' '}
          <a href="https://giovannivillage.com">https://giovannivillage.com</a>.
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company or other legal
          entity on behalf of which such individual is accessing or using the Service.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Personal Data</h3>
      <p>
        While using our Service, we may ask you to provide certain personally identifiable information that can be used
        to contact or identify you. Personally identifiable information may include, but is not limited to:
      </p>
      <ul>
        <li>Name</li>
        <li>Phone number</li>
        <li>Email address</li>
        <li>Usage data</li>
      </ul>

      <h3>Usage Data</h3>
      <p>
        Usage Data is collected automatically when using the Service. It may include information such as your device&apos;s
        IP address, browser type, browser version, the pages of our Service that you visit, the time and date of your
        visit, the time spent on those pages, and other diagnostic data.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use cookies and similar tracking technologies to track activity on our Service and store certain
        information. Tracking technologies used include beacons, tags and scripts to collect and track information and
        improve our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being
        sent.
      </p>

      <h2>Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service.</li>
        <li>To manage your account and bookings.</li>
        <li>To contact you regarding your reservation, updates or related services.</li>
        <li>To respond to your enquiries and customer support requests.</li>
        <li>For analysis, identifying usage trends and improving our Service.</li>
      </ul>

      <h2>Security of Your Personal Data</h2>
      <p>
        The security of your Personal Data is important to us, but no method of transmission over the Internet or
        method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect
        your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
        information from anyone under the age of 13.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
        Privacy Policy on this page and updating the &ldquo;Last updated&rdquo; date.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, you can contact us by email at{' '}
        <a href="mailto:reservations@giovannivillage.com">reservations@giovannivillage.com</a>.
      </p>
    </LegalLayout>
  );
}
